sonar.projectKey=NT548-lab2-b3
sonar.projectName=NT548 DevOps Lab 2
sonar.sources=.
sonar.exclusions=**/__tests__/**,**/node_modules/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=https://sonarcloud.io
sonar.organization=nguyentrantuankhoi
